name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add Sqlite Dep
      run: sudo apt install libsqlite3-dev
    - name: Generate Style
      run: npm install && npm run style
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose